// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back_end.domain.DbContexts;

#nullable disable

namespace back_end.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("back_end.domain.Entities.Billing", b =>
                {
                    b.Property<int>("Bill_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Bill_Id"));

                    b.Property<int>("Adult_Count")
                        .HasColumnType("int");

                    b.Property<string>("Bill_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Child_Count")
                        .HasColumnType("int");

                    b.Property<string>("Closed_At")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Senior_Count")
                        .HasColumnType("int");

                    b.Property<int>("Session_Id")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Total_Count")
                        .HasColumnType("int");

                    b.HasKey("Bill_Id");

                    b.HasIndex("Session_Id");

                    b.ToTable("bills");

                    b.HasData(
                        new
                        {
                            Bill_Id = 1,
                            Adult_Count = 2,
                            Bill_Name = "Table 1-2 Lunch",
                            Child_Count = 0,
                            Created_At = new DateTime(2024, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Senior_Count = 0,
                            Session_Id = 1,
                            Status = 0,
                            Total_Count = 2
                        },
                        new
                        {
                            Bill_Id = 2,
                            Adult_Count = 1,
                            Bill_Name = "Table 3 Dinner",
                            Child_Count = 0,
                            Created_At = new DateTime(2024, 10, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Senior_Count = 0,
                            Session_Id = 2,
                            Status = 0,
                            Total_Count = 1
                        },
                        new
                        {
                            Bill_Id = 3,
                            Adult_Count = 1,
                            Bill_Name = "Table 4 Brunch",
                            Child_Count = 0,
                            Created_At = new DateTime(2024, 10, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Senior_Count = 0,
                            Session_Id = 3,
                            Status = 1,
                            Total_Count = 1
                        });
                });

            modelBuilder.Entity("back_end.domain.Entities.Category", b =>
                {
                    b.Property<int>("Category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Category_id"));

                    b.Property<string>("Category_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("adult_limit")
                        .HasColumnType("int");

                    b.Property<int>("child_limit")
                        .HasColumnType("int");

                    b.Property<string>("image_url")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("last_viewed_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("senior_limit")
                        .HasColumnType("int");

                    b.Property<int>("total_limit")
                        .HasColumnType("int");

                    b.Property<int>("total_view_seconds")
                        .HasColumnType("int");

                    b.Property<int>("total_views")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.HasKey("Category_id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Category_id = 1,
                            Category_name = "Appetizers",
                            Description = "Start your meal with these delicious appetizers",
                            adult_limit = 0,
                            child_limit = 0,
                            last_viewed_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            senior_limit = 0,
                            total_limit = 0,
                            total_view_seconds = 0,
                            total_views = 0
                        },
                        new
                        {
                            Category_id = 2,
                            Category_name = "Main Courses",
                            Description = "Hearty main dishes to satisfy your hunger",
                            adult_limit = 0,
                            child_limit = 0,
                            last_viewed_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            senior_limit = 0,
                            total_limit = 0,
                            total_view_seconds = 0,
                            total_views = 0
                        },
                        new
                        {
                            Category_id = 3,
                            Category_name = "Desserts",
                            Description = "Sweet treats to end your meal",
                            adult_limit = 0,
                            child_limit = 0,
                            last_viewed_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            senior_limit = 0,
                            total_limit = 0,
                            total_view_seconds = 0,
                            total_views = 0
                        },
                        new
                        {
                            Category_id = 4,
                            Category_name = "Beverages",
                            Description = "Refreshing drinks and cocktails",
                            adult_limit = 0,
                            child_limit = 0,
                            last_viewed_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            senior_limit = 0,
                            total_limit = 0,
                            total_view_seconds = 0,
                            total_views = 0
                        },
                        new
                        {
                            Category_id = 5,
                            Category_name = "Salads",
                            Description = "Fresh and healthy salad options",
                            adult_limit = 0,
                            child_limit = 0,
                            last_viewed_at = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            senior_limit = 0,
                            total_limit = 0,
                            total_view_seconds = 0,
                            total_views = 0
                        });
                });

            modelBuilder.Entity("back_end.domain.Entities.DiningSession", b =>
                {
                    b.Property<int>("Session_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Session_Id"));

                    b.Property<DateTime?>("Ended_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("First_Order_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Menu_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Started_At")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Session_Id");

                    b.HasIndex("Menu_Id");

                    b.ToTable("dining_sessions");

                    b.HasData(
                        new
                        {
                            Session_Id = 1,
                            First_Order_At = new DateTime(2024, 10, 1, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            Menu_Id = 2,
                            Started_At = new DateTime(2024, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Session_Id = 2,
                            First_Order_At = new DateTime(2024, 10, 1, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Menu_Id = 3,
                            Started_At = new DateTime(2024, 10, 1, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Session_Id = 3,
                            First_Order_At = new DateTime(2024, 10, 2, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Menu_Id = 4,
                            Started_At = new DateTime(2024, 10, 2, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("back_end.domain.Entities.Locations", b =>
                {
                    b.Property<int>("Location_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Location_Id"));

                    b.Property<string>("Address_Primary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Address_Secondary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone_Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Postal_Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Location_Id");

                    b.ToTable("locations");

                    b.HasData(
                        new
                        {
                            Location_Id = 1,
                            Address_Primary = "123 Main St",
                            Address_Secondary = "",
                            City = "Edmonton",
                            Created_At = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Downtown Branch",
                            Phone_Number = "780-555-0101",
                            Postal_Code = "T5K 2P6",
                            Province = "Alberta",
                            Updated_At = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Location_Id = 2,
                            Address_Primary = "456 West Ave",
                            Address_Secondary = "",
                            City = "Edmonton",
                            Created_At = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "West End Branch",
                            Phone_Number = "780-555-0102",
                            Postal_Code = "T5L 3R8",
                            Province = "Alberta",
                            Updated_At = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Location_Id = 3,
                            Address_Primary = "789 South Rd",
                            Address_Secondary = "",
                            City = "Edmonton",
                            Created_At = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "South Side Branch",
                            Phone_Number = "780-555-0103",
                            Postal_Code = "T6G 1M2",
                            Province = "Alberta",
                            Updated_At = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("back_end.domain.Entities.Menu", b =>
                {
                    b.Property<int>("Menu_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Menu_id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("End_time")
                        .HasColumnType("time(6)");

                    b.Property<bool>("Is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("Start_time")
                        .HasColumnType("time(6)");

                    b.HasKey("Menu_id");

                    b.ToTable("menu");

                    b.HasData(
                        new
                        {
                            Menu_id = 1,
                            Description = "Available until 11 AM",
                            End_time = new TimeOnly(11, 0, 0),
                            Is_active = true,
                            Name = "Breakfast Menu",
                            Start_time = new TimeOnly(6, 0, 0)
                        },
                        new
                        {
                            Menu_id = 2,
                            Description = "Midday favorites",
                            End_time = new TimeOnly(16, 0, 0),
                            Is_active = true,
                            Name = "Lunch Menu",
                            Start_time = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Menu_id = 3,
                            Description = "Evening specials",
                            End_time = new TimeOnly(22, 0, 0),
                            Is_active = true,
                            Name = "Dinner Menu",
                            Start_time = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Menu_id = 4,
                            Description = "Special weekend offerings",
                            End_time = new TimeOnly(15, 0, 0),
                            Is_active = true,
                            Name = "Weekend Brunch",
                            Start_time = new TimeOnly(9, 0, 0)
                        });
                });

            modelBuilder.Entity("back_end.domain.Entities.MenuItemAssignment", b =>
                {
                    b.Property<int>("Menu_Id")
                        .HasColumnType("int")
                        .HasColumnName("menu_id");

                    b.Property<int>("Item_Id")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int>("Adult_Limit")
                        .HasColumnType("int");

                    b.Property<int>("Child_limit")
                        .HasColumnType("int");

                    b.Property<bool>("Is_Add_On")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastOrdered")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Senior_limit")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Total_Limit")
                        .HasColumnType("int");

                    b.Property<int>("Total_Units_Ordered")
                        .HasColumnType("int");

                    b.Property<int>("Total_View_Seconds")
                        .HasColumnType("int");

                    b.Property<int>("Total_Views")
                        .HasColumnType("int");

                    b.HasKey("Menu_Id", "Item_Id");

                    b.HasIndex("Item_Id");

                    b.ToTable("menu_item_assignment");

                    b.HasData(
                        new
                        {
                            Menu_Id = 2,
                            Item_Id = 1,
                            Adult_Limit = 0,
                            Child_limit = 0,
                            Is_Add_On = false,
                            LastOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 12.99m,
                            Senior_limit = 0,
                            Status = 0,
                            Total_Limit = 0,
                            Total_Units_Ordered = 0,
                            Total_View_Seconds = 0,
                            Total_Views = 0
                        },
                        new
                        {
                            Menu_Id = 2,
                            Item_Id = 2,
                            Adult_Limit = 0,
                            Child_limit = 0,
                            Is_Add_On = false,
                            LastOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 8.99m,
                            Senior_limit = 0,
                            Status = 0,
                            Total_Limit = 0,
                            Total_Units_Ordered = 0,
                            Total_View_Seconds = 0,
                            Total_Views = 0
                        },
                        new
                        {
                            Menu_Id = 2,
                            Item_Id = 3,
                            Adult_Limit = 0,
                            Child_limit = 0,
                            Is_Add_On = false,
                            LastOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 9.99m,
                            Senior_limit = 0,
                            Status = 0,
                            Total_Limit = 0,
                            Total_Units_Ordered = 0,
                            Total_View_Seconds = 0,
                            Total_Views = 0
                        },
                        new
                        {
                            Menu_Id = 2,
                            Item_Id = 5,
                            Adult_Limit = 0,
                            Child_limit = 0,
                            Is_Add_On = false,
                            LastOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 15.99m,
                            Senior_limit = 0,
                            Status = 0,
                            Total_Limit = 0,
                            Total_Units_Ordered = 0,
                            Total_View_Seconds = 0,
                            Total_Views = 0
                        },
                        new
                        {
                            Menu_Id = 3,
                            Item_Id = 1,
                            Adult_Limit = 0,
                            Child_limit = 0,
                            Is_Add_On = false,
                            LastOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 13.99m,
                            Senior_limit = 0,
                            Status = 0,
                            Total_Limit = 0,
                            Total_Units_Ordered = 0,
                            Total_View_Seconds = 0,
                            Total_Views = 0
                        },
                        new
                        {
                            Menu_Id = 3,
                            Item_Id = 4,
                            Adult_Limit = 0,
                            Child_limit = 0,
                            Is_Add_On = false,
                            LastOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 24.99m,
                            Senior_limit = 0,
                            Status = 0,
                            Total_Limit = 0,
                            Total_Units_Ordered = 0,
                            Total_View_Seconds = 0,
                            Total_Views = 0
                        },
                        new
                        {
                            Menu_Id = 3,
                            Item_Id = 5,
                            Adult_Limit = 0,
                            Child_limit = 0,
                            Is_Add_On = false,
                            LastOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 16.99m,
                            Senior_limit = 0,
                            Status = 0,
                            Total_Limit = 0,
                            Total_Units_Ordered = 0,
                            Total_View_Seconds = 0,
                            Total_Views = 0
                        },
                        new
                        {
                            Menu_Id = 3,
                            Item_Id = 6,
                            Adult_Limit = 0,
                            Child_limit = 0,
                            Is_Add_On = false,
                            LastOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 18.99m,
                            Senior_limit = 0,
                            Status = 0,
                            Total_Limit = 0,
                            Total_Units_Ordered = 0,
                            Total_View_Seconds = 0,
                            Total_Views = 0
                        },
                        new
                        {
                            Menu_Id = 3,
                            Item_Id = 7,
                            Adult_Limit = 0,
                            Child_limit = 0,
                            Is_Add_On = false,
                            LastOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 7.99m,
                            Senior_limit = 0,
                            Status = 0,
                            Total_Limit = 0,
                            Total_Units_Ordered = 0,
                            Total_View_Seconds = 0,
                            Total_Views = 0
                        },
                        new
                        {
                            Menu_Id = 4,
                            Item_Id = 3,
                            Adult_Limit = 0,
                            Child_limit = 0,
                            Is_Add_On = false,
                            LastOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 11.99m,
                            Senior_limit = 0,
                            Status = 0,
                            Total_Limit = 0,
                            Total_Units_Ordered = 0,
                            Total_View_Seconds = 0,
                            Total_Views = 0
                        },
                        new
                        {
                            Menu_Id = 4,
                            Item_Id = 8,
                            Adult_Limit = 0,
                            Child_limit = 0,
                            Is_Add_On = false,
                            LastOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 6.99m,
                            Senior_limit = 0,
                            Status = 0,
                            Total_Limit = 0,
                            Total_Units_Ordered = 0,
                            Total_View_Seconds = 0,
                            Total_Views = 0
                        },
                        new
                        {
                            Menu_Id = 4,
                            Item_Id = 9,
                            Adult_Limit = 0,
                            Child_limit = 0,
                            Is_Add_On = false,
                            LastOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 5.99m,
                            Senior_limit = 0,
                            Status = 0,
                            Total_Limit = 0,
                            Total_Units_Ordered = 0,
                            Total_View_Seconds = 0,
                            Total_Views = 0
                        },
                        new
                        {
                            Menu_Id = 4,
                            Item_Id = 10,
                            Adult_Limit = 0,
                            Child_limit = 0,
                            Is_Add_On = false,
                            LastOrdered = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 3.99m,
                            Senior_limit = 0,
                            Status = 0,
                            Total_Limit = 0,
                            Total_Units_Ordered = 0,
                            Total_View_Seconds = 0,
                            Total_Views = 0
                        });
                });

            modelBuilder.Entity("back_end.domain.Entities.MenuItemTag", b =>
                {
                    b.Property<int>("Menu_item_id")
                        .HasColumnType("int");

                    b.Property<int>("Tag_id")
                        .HasColumnType("int");

                    b.HasKey("Menu_item_id", "Tag_id");

                    b.HasIndex("Tag_id");

                    b.ToTable("menu_item_tag");

                    b.HasData(
                        new
                        {
                            Menu_item_id = 3,
                            Tag_id = 1
                        },
                        new
                        {
                            Menu_item_id = 6,
                            Tag_id = 1
                        },
                        new
                        {
                            Menu_item_id = 6,
                            Tag_id = 2
                        },
                        new
                        {
                            Menu_item_id = 1,
                            Tag_id = 4
                        },
                        new
                        {
                            Menu_item_id = 1,
                            Tag_id = 5
                        },
                        new
                        {
                            Menu_item_id = 5,
                            Tag_id = 5
                        },
                        new
                        {
                            Menu_item_id = 10,
                            Tag_id = 6
                        });
                });

            modelBuilder.Entity("back_end.domain.Entities.MenuLocations", b =>
                {
                    b.Property<int>("Menu_Id")
                        .HasColumnType("int");

                    b.Property<int>("Location_Id")
                        .HasColumnType("int");

                    b.HasKey("Menu_Id", "Location_Id");

                    b.HasIndex("Location_Id");

                    b.ToTable("menu_location");

                    b.HasData(
                        new
                        {
                            Menu_Id = 1,
                            Location_Id = 1
                        },
                        new
                        {
                            Menu_Id = 2,
                            Location_Id = 1
                        },
                        new
                        {
                            Menu_Id = 3,
                            Location_Id = 1
                        },
                        new
                        {
                            Menu_Id = 2,
                            Location_Id = 2
                        },
                        new
                        {
                            Menu_Id = 3,
                            Location_Id = 2
                        },
                        new
                        {
                            Menu_Id = 4,
                            Location_Id = 3
                        });
                });

            modelBuilder.Entity("back_end.domain.Entities.Menu_Item", b =>
                {
                    b.Property<int>("item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("item_id"));

                    b.Property<int>("Category_id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("image_url")
                        .HasColumnType("longtext");

                    b.HasKey("item_id");

                    b.HasIndex("Category_id");

                    b.ToTable("menu_item");

                    b.HasData(
                        new
                        {
                            item_id = 1,
                            Category_id = 1,
                            Description = "Crispy chicken wings with spicy buffalo sauce",
                            Name = "Buffalo Wings",
                            Status = 0
                        },
                        new
                        {
                            item_id = 2,
                            Category_id = 1,
                            Description = "Golden fried mozzarella with marinara sauce",
                            Name = "Mozzarella Sticks",
                            Status = 0
                        },
                        new
                        {
                            item_id = 3,
                            Category_id = 5,
                            Description = "Crisp romaine lettuce with Caesar dressing",
                            Name = "Caesar Salad",
                            Status = 0
                        },
                        new
                        {
                            item_id = 4,
                            Category_id = 2,
                            Description = "Fresh Atlantic salmon with lemon herb butter",
                            Name = "Grilled Salmon",
                            Status = 0
                        },
                        new
                        {
                            item_id = 5,
                            Category_id = 2,
                            Description = "Juicy beef patty with all the fixings",
                            Name = "Beef Burger",
                            Status = 0
                        },
                        new
                        {
                            item_id = 6,
                            Category_id = 2,
                            Description = "Penne pasta with seasonal vegetables",
                            Name = "Vegetarian Pasta",
                            Status = 0
                        },
                        new
                        {
                            item_id = 7,
                            Category_id = 3,
                            Description = "Rich chocolate layer cake",
                            Name = "Chocolate Cake",
                            Status = 0
                        },
                        new
                        {
                            item_id = 8,
                            Category_id = 3,
                            Description = "Vanilla ice cream with toppings",
                            Name = "Ice Cream Sundae",
                            Status = 0
                        },
                        new
                        {
                            item_id = 9,
                            Category_id = 4,
                            Description = "Local brewery selection",
                            Name = "Craft Beer",
                            Status = 0
                        },
                        new
                        {
                            item_id = 10,
                            Category_id = 4,
                            Description = "House-made lemonade",
                            Name = "Fresh Lemonade",
                            Status = 0
                        });
                });

            modelBuilder.Entity("back_end.domain.Entities.OrderItems", b =>
                {
                    b.Property<int>("Order_Item_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Order_Item_Id"));

                    b.Property<DateTime?>("Completed_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Item_Id")
                        .HasColumnType("int");

                    b.Property<int>("Menu_Id")
                        .HasColumnType("int");

                    b.Property<int>("Order_Item_Status")
                        .HasColumnType("int");

                    b.Property<int>("Order_Key")
                        .HasColumnType("int");

                    b.Property<decimal>("Price_At_Time")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Order_Item_Id");

                    b.HasIndex("Item_Id");

                    b.HasIndex("Menu_Id");

                    b.HasIndex("Order_Key");

                    b.ToTable("order_item");

                    b.HasData(
                        new
                        {
                            Order_Item_Id = 1,
                            Completed_At = new DateTime(2024, 10, 1, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            Item_Id = 1,
                            Menu_Id = 2,
                            Order_Item_Status = 2,
                            Order_Key = 1,
                            Price_At_Time = 12.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Order_Item_Id = 2,
                            Completed_At = new DateTime(2024, 10, 1, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            Item_Id = 3,
                            Menu_Id = 2,
                            Order_Item_Status = 2,
                            Order_Key = 1,
                            Price_At_Time = 9.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Order_Item_Id = 3,
                            Completed_At = new DateTime(2024, 10, 1, 12, 50, 0, 0, DateTimeKind.Unspecified),
                            Item_Id = 5,
                            Menu_Id = 2,
                            Order_Item_Status = 2,
                            Order_Key = 2,
                            Price_At_Time = 15.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Order_Item_Id = 4,
                            Item_Id = 4,
                            Menu_Id = 3,
                            Order_Item_Status = 1,
                            Order_Key = 3,
                            Price_At_Time = 24.99m,
                            Quantity = 1
                        },
                        new
                        {
                            Order_Item_Id = 5,
                            Completed_At = new DateTime(2024, 10, 2, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            Item_Id = 8,
                            Menu_Id = 4,
                            Order_Item_Status = 2,
                            Order_Key = 4,
                            Price_At_Time = 6.99m,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("back_end.domain.Entities.ServiceRequest", b =>
                {
                    b.Property<int>("request_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("request_id"));

                    b.Property<DateTime?>("Claimed_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Claimed_By")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Completed_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Request_By")
                        .HasColumnType("int");

                    b.Property<int>("Session_Id")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Table_Id")
                        .HasColumnType("int");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.Property<int?>("User_id1")
                        .HasColumnType("int");

                    b.HasKey("request_id");

                    b.HasIndex("Claimed_By");

                    b.HasIndex("Request_By");

                    b.HasIndex("Session_Id");

                    b.HasIndex("Table_Id");

                    b.HasIndex("User_id");

                    b.HasIndex("User_id1");

                    b.ToTable("service_request");

                    b.HasData(
                        new
                        {
                            request_id = 1,
                            Claimed_At = new DateTime(2024, 10, 1, 12, 32, 0, 0, DateTimeKind.Unspecified),
                            Claimed_By = 2,
                            Completed_At = new DateTime(2024, 10, 1, 12, 35, 0, 0, DateTimeKind.Unspecified),
                            Created_At = new DateTime(2024, 10, 1, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Need extra napkins",
                            Request_By = 1,
                            Session_Id = 1,
                            Status = 2,
                            Table_Id = 1
                        },
                        new
                        {
                            request_id = 2,
                            Created_At = new DateTime(2024, 10, 1, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Check on food order",
                            Request_By = 1,
                            Session_Id = 2,
                            Status = 0,
                            Table_Id = 3
                        },
                        new
                        {
                            request_id = 3,
                            Claimed_At = new DateTime(2024, 10, 2, 11, 2, 0, 0, DateTimeKind.Unspecified),
                            Claimed_By = 3,
                            Completed_At = new DateTime(2024, 10, 2, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            Created_At = new DateTime(2024, 10, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Request the bill",
                            Request_By = 5,
                            Session_Id = 3,
                            Status = 2,
                            Table_Id = 4
                        });
                });

            modelBuilder.Entity("back_end.domain.Entities.SessionOrder", b =>
                {
                    b.Property<int>("Order_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Order_Id"));

                    b.Property<int>("Bill_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Completed_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.Property<int>("session_id")
                        .HasColumnType("int");

                    b.HasKey("Order_Id");

                    b.HasIndex("Bill_Id");

                    b.HasIndex("User_Id");

                    b.HasIndex("session_id");

                    b.ToTable("session_order");

                    b.HasData(
                        new
                        {
                            Order_Id = 1,
                            Bill_Id = 1,
                            Completed_At = new DateTime(2024, 10, 1, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            Created_At = new DateTime(2024, 10, 1, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            User_Id = 1,
                            session_id = 1
                        },
                        new
                        {
                            Order_Id = 2,
                            Bill_Id = 1,
                            Completed_At = new DateTime(2024, 10, 1, 12, 50, 0, 0, DateTimeKind.Unspecified),
                            Created_At = new DateTime(2024, 10, 1, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            User_Id = 5,
                            session_id = 1
                        },
                        new
                        {
                            Order_Id = 3,
                            Bill_Id = 2,
                            Created_At = new DateTime(2024, 10, 1, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            User_Id = 1,
                            session_id = 2
                        },
                        new
                        {
                            Order_Id = 4,
                            Bill_Id = 3,
                            Completed_At = new DateTime(2024, 10, 2, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            Created_At = new DateTime(2024, 10, 2, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            User_Id = 5,
                            session_id = 3
                        });
                });

            modelBuilder.Entity("back_end.domain.Entities.SessionParticipant", b =>
                {
                    b.Property<int>("Session_Id")
                        .HasColumnType("int");

                    b.Property<int>("User_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Joined_At")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Left_At")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Participant_Id")
                        .HasColumnType("int");

                    b.HasKey("Session_Id", "User_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("session_participant");

                    b.HasData(
                        new
                        {
                            Session_Id = 1,
                            User_Id = 1,
                            Joined_At = new DateTime(2024, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Participant_Id = 1
                        },
                        new
                        {
                            Session_Id = 1,
                            User_Id = 5,
                            Joined_At = new DateTime(2024, 10, 1, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            Participant_Id = 2
                        },
                        new
                        {
                            Session_Id = 2,
                            User_Id = 1,
                            Joined_At = new DateTime(2024, 10, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Participant_Id = 3
                        },
                        new
                        {
                            Session_Id = 3,
                            User_Id = 5,
                            Joined_At = new DateTime(2024, 10, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Participant_Id = 4
                        });
                });

            modelBuilder.Entity("back_end.domain.Entities.Sessions", b =>
                {
                    b.Property<int>("Session_Id")
                        .HasColumnType("int");

                    b.Property<int>("Table_Id")
                        .HasColumnType("int");

                    b.HasKey("Session_Id", "Table_Id");

                    b.HasIndex("Table_Id");

                    b.ToTable("sessions");

                    b.HasData(
                        new
                        {
                            Session_Id = 1,
                            Table_Id = 1
                        },
                        new
                        {
                            Session_Id = 1,
                            Table_Id = 2
                        },
                        new
                        {
                            Session_Id = 2,
                            Table_Id = 3
                        },
                        new
                        {
                            Session_Id = 3,
                            Table_Id = 4
                        });
                });

            modelBuilder.Entity("back_end.domain.Entities.TableEntity", b =>
                {
                    b.Property<int>("Table_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Table_Id"));

                    b.Property<string>("QR_Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("seat_count")
                        .HasColumnType("int");

                    b.Property<int>("table_number")
                        .HasColumnType("int");

                    b.HasKey("Table_Id");

                    b.ToTable("table_entity");

                    b.HasData(
                        new
                        {
                            Table_Id = 1,
                            QR_Code = "QR101",
                            is_active = true,
                            seat_count = 4,
                            table_number = 101
                        },
                        new
                        {
                            Table_Id = 2,
                            QR_Code = "QR102",
                            is_active = true,
                            seat_count = 2,
                            table_number = 102
                        },
                        new
                        {
                            Table_Id = 3,
                            QR_Code = "QR103",
                            is_active = true,
                            seat_count = 6,
                            table_number = 103
                        },
                        new
                        {
                            Table_Id = 4,
                            QR_Code = "QR104",
                            is_active = true,
                            seat_count = 4,
                            table_number = 104
                        },
                        new
                        {
                            Table_Id = 5,
                            QR_Code = "QR105",
                            is_active = true,
                            seat_count = 8,
                            table_number = 105
                        });
                });

            modelBuilder.Entity("back_end.domain.Entities.Tag", b =>
                {
                    b.Property<int>("tag_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("tag_id"));

                    b.Property<string>("tag_color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("tag_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("tag_id");

                    b.ToTable("tag");

                    b.HasData(
                        new
                        {
                            tag_id = 1,
                            tag_color = "#00FF00",
                            tag_name = "Vegetarian"
                        },
                        new
                        {
                            tag_id = 2,
                            tag_color = "#008000",
                            tag_name = "Vegan"
                        },
                        new
                        {
                            tag_id = 3,
                            tag_color = "#FFD700",
                            tag_name = "Gluten-Free"
                        },
                        new
                        {
                            tag_id = 4,
                            tag_color = "#FF0000",
                            tag_name = "Spicy"
                        },
                        new
                        {
                            tag_id = 5,
                            tag_color = "#FF69B4",
                            tag_name = "Popular"
                        },
                        new
                        {
                            tag_id = 6,
                            tag_color = "#32CD32",
                            tag_name = "Organic"
                        });
                });

            modelBuilder.Entity("back_end.domain.Entities.User", b =>
                {
                    b.Property<int>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("User_id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Is_email_confirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("Last_Interaction_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Normalized_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("User_id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            User_id = 1,
                            Created_at = new DateTime(2025, 10, 1, 21, 39, 37, 656, DateTimeKind.Local).AddTicks(9514),
                            Email = "john.doe@example.com",
                            First_name = "John",
                            Is_email_confirmed = false,
                            Last_name = "Doe",
                            Normalized_email = "JOHN.DOE@EXAMPLE.COM",
                            Password_hash = "hashed_password_1",
                            Role = 2,
                            Status = 0
                        },
                        new
                        {
                            User_id = 2,
                            Created_at = new DateTime(2025, 10, 1, 21, 39, 37, 657, DateTimeKind.Local).AddTicks(295),
                            Email = "jane.smith@example.com",
                            First_name = "Jane",
                            Is_email_confirmed = false,
                            Last_name = "Smith",
                            Normalized_email = "JANE.SMITH@EXAMPLE.COM",
                            Password_hash = "hashed_password_2",
                            Role = 1,
                            Status = 0
                        },
                        new
                        {
                            User_id = 3,
                            Created_at = new DateTime(2025, 10, 1, 21, 39, 37, 657, DateTimeKind.Local).AddTicks(302),
                            Email = "bob.johnson@example.com",
                            First_name = "Bob",
                            Is_email_confirmed = false,
                            Last_name = "Johnson",
                            Normalized_email = "BOB.JOHNSON@EXAMPLE.COM",
                            Password_hash = "hashed_password_3",
                            Role = 1,
                            Status = 0
                        },
                        new
                        {
                            User_id = 4,
                            Created_at = new DateTime(2025, 10, 1, 21, 39, 37, 657, DateTimeKind.Local).AddTicks(304),
                            Email = "alice.wilson@example.com",
                            First_name = "Alice",
                            Is_email_confirmed = false,
                            Last_name = "Wilson",
                            Normalized_email = "ALICE.WILSON@EXAMPLE.COM",
                            Password_hash = "hashed_password_4",
                            Role = 0,
                            Status = 0
                        },
                        new
                        {
                            User_id = 5,
                            Created_at = new DateTime(2025, 10, 1, 21, 39, 37, 657, DateTimeKind.Local).AddTicks(307),
                            Email = "mike.brown@example.com",
                            First_name = "Mike",
                            Is_email_confirmed = false,
                            Last_name = "Brown",
                            Normalized_email = "MIKE.BROWN@EXAMPLE.COM",
                            Password_hash = "hashed_password_5",
                            Role = 2,
                            Status = 0
                        });
                });

            modelBuilder.Entity("back_end.domain.Entities.Billing", b =>
                {
                    b.HasOne("back_end.domain.Entities.DiningSession", "DiningSession")
                        .WithMany("Bills")
                        .HasForeignKey("Session_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiningSession");
                });

            modelBuilder.Entity("back_end.domain.Entities.DiningSession", b =>
                {
                    b.HasOne("back_end.domain.Entities.Menu", "Menu")
                        .WithMany("DiningSessions")
                        .HasForeignKey("Menu_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("back_end.domain.Entities.MenuItemAssignment", b =>
                {
                    b.HasOne("back_end.domain.Entities.Menu_Item", "MenuItem")
                        .WithMany("MenuAssignments")
                        .HasForeignKey("Item_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.Menu", "Menu")
                        .WithMany("MenuItemAssignments")
                        .HasForeignKey("Menu_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("back_end.domain.Entities.MenuItemTag", b =>
                {
                    b.HasOne("back_end.domain.Entities.Menu_Item", "MenuItem")
                        .WithMany("MenuItemTags")
                        .HasForeignKey("Menu_item_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.Tag", "Tag")
                        .WithMany("MenuItemTags")
                        .HasForeignKey("Tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("back_end.domain.Entities.MenuLocations", b =>
                {
                    b.HasOne("back_end.domain.Entities.Locations", "Location")
                        .WithMany("MenuLocations")
                        .HasForeignKey("Location_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.Menu", "Menu")
                        .WithMany("MenuLocations")
                        .HasForeignKey("Menu_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("back_end.domain.Entities.Menu_Item", b =>
                {
                    b.HasOne("back_end.domain.Entities.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("Category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("back_end.domain.Entities.OrderItems", b =>
                {
                    b.HasOne("back_end.domain.Entities.Menu_Item", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("Item_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.Menu", "Menu")
                        .WithMany("OrderItems")
                        .HasForeignKey("Menu_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.SessionOrder", "SessionOrder")
                        .WithMany("OrderItems")
                        .HasForeignKey("Order_Key")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("MenuItem");

                    b.Navigation("SessionOrder");
                });

            modelBuilder.Entity("back_end.domain.Entities.ServiceRequest", b =>
                {
                    b.HasOne("back_end.domain.Entities.User", "ClaimedByUser")
                        .WithMany()
                        .HasForeignKey("Claimed_By")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("back_end.domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("Request_By")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.DiningSession", "DiningSession")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("Session_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.TableEntity", "Table")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("Table_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.User", null)
                        .WithMany("ClaimedServices")
                        .HasForeignKey("User_id");

                    b.HasOne("back_end.domain.Entities.User", null)
                        .WithMany("RequestedServices")
                        .HasForeignKey("User_id1");

                    b.Navigation("ClaimedByUser");

                    b.Navigation("DiningSession");

                    b.Navigation("RequestedByUser");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("back_end.domain.Entities.SessionOrder", b =>
                {
                    b.HasOne("back_end.domain.Entities.Billing", "Bill")
                        .WithMany("Orders")
                        .HasForeignKey("Bill_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.DiningSession", "DiningSession")
                        .WithMany("Orders")
                        .HasForeignKey("session_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("DiningSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("back_end.domain.Entities.SessionParticipant", b =>
                {
                    b.HasOne("back_end.domain.Entities.DiningSession", "DiningSession")
                        .WithMany("Participants")
                        .HasForeignKey("Session_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.User", "User")
                        .WithMany("SessionParticipants")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiningSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("back_end.domain.Entities.Sessions", b =>
                {
                    b.HasOne("back_end.domain.Entities.DiningSession", "DiningSession")
                        .WithMany("Sessions")
                        .HasForeignKey("Session_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.domain.Entities.TableEntity", "Table")
                        .WithMany("Sessions")
                        .HasForeignKey("Table_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiningSession");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("back_end.domain.Entities.Billing", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("back_end.domain.Entities.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("back_end.domain.Entities.DiningSession", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Orders");

                    b.Navigation("Participants");

                    b.Navigation("ServiceRequests");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("back_end.domain.Entities.Locations", b =>
                {
                    b.Navigation("MenuLocations");
                });

            modelBuilder.Entity("back_end.domain.Entities.Menu", b =>
                {
                    b.Navigation("DiningSessions");

                    b.Navigation("MenuItemAssignments");

                    b.Navigation("MenuLocations");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("back_end.domain.Entities.Menu_Item", b =>
                {
                    b.Navigation("MenuAssignments");

                    b.Navigation("MenuItemTags");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("back_end.domain.Entities.SessionOrder", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("back_end.domain.Entities.TableEntity", b =>
                {
                    b.Navigation("ServiceRequests");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("back_end.domain.Entities.Tag", b =>
                {
                    b.Navigation("MenuItemTags");
                });

            modelBuilder.Entity("back_end.domain.Entities.User", b =>
                {
                    b.Navigation("ClaimedServices");

                    b.Navigation("Orders");

                    b.Navigation("RequestedServices");

                    b.Navigation("SessionParticipants");
                });
#pragma warning restore 612, 618
        }
    }
}
