"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

import { ThemeProvider, CssBaseline } from "@mui/material";
import { createTheme } from "@mui/material/styles";
import { MenuProvider } from "@/contexts/MenuContext";
import { NotificationProvider } from "@/contexts/NotificationContext";
import { OrderProvider } from "@/contexts/OrderContext";
import NotificationSystem from "@/components/common/NotificationSystem";
import Layout from "@/components/Layout.jsx";
import "@/styles/global.css";

import { MsalProvider } from "@azure/msal-react";
import msalInstance from "@/config/msalInstance";
import { useEffect, useState, createContext } from "react";
import { silentRequest } from "@/config/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const theme = createTheme({
  palette: {
    primary: {
      main: "#C01E2E",
    },
    secondary: {
      main: "#14171a",
    },
    text: {
      primary: "#000000",
      secondary: "#657786",
    },
    background: {
      default: "#ffffff",
      paper: "#ffffff",
    },
  },
  typography: {
    fontFamily: "'Open Sans', sans-serif",
    h1: {
      fontFamily: "'Montserrat', sans-serif",
      fontWeight: 600,
    },
    h2: {
      fontFamily: "'Montserrat', sans-serif",
      fontWeight: 600,
    },
    h3: {
      fontFamily: "'Montserrat', sans-serif",
      fontWeight: 600,
    },
    h4: {
      fontFamily: "'Montserrat', sans-serif",
      fontWeight: 600,
    },
    h5: {
      fontFamily: "'Montserrat', sans-serif",
      fontWeight: 600,
    },
    h6: {
      fontFamily: "'Montserrat', sans-serif",
      fontWeight: 600,
    },
  },
  components: {
    MuiButton: {
      styleOverrides: {
        root: {
          textTransform: "none",
          borderRadius: "4px",
        },
      },
    },
    MuiDialog: {
      styleOverrides: {
        paper: {
          borderRadius: 8,
        },
      },
    },
    MuiAppBar: {
      styleOverrides: {
        root: {
          backgroundColor: "#C01E2E",
        },
      },
    },
  },
});

export const AuthContext = createContext();

export default function RootLayout({ children }) {
  const [activeAccount, setActiveAccount] = useState(null);
  const [userRole, setUserRole] = useState(null);
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [roles, setRoles] = useState([]);
  const [authLoading, setAuthLoading] = useState(true);

  useEffect(() => {
    // Only run on client
    if (typeof window === "undefined") return;

    let isMounted = true;
    setAuthLoading(true);

    msalInstance.initialize().then(() => {
      if (!isMounted) return;
      const accounts = msalInstance.getAllAccounts();
      const account = accounts && accounts.length > 0 ? accounts[0] : null;
      if (account) {
        msalInstance.setActiveAccount(account);
        setActiveAccount(account);
        setIsLoggedIn(true);
        msalInstance
          .acquireTokenSilent({ ...silentRequest, account })
          .then((response) => {
            let rawRoles =
              response.idTokenClaims?.roles ||
              response.idTokenClaims?.role ||
              [];
            const roleList = Array.isArray(rawRoles) ? rawRoles : [rawRoles];
            setRoles(roleList);
            if (roleList.includes("user.Admin")) setUserRole("admin");
            else if (roleList.includes("user.Staff")) setUserRole("staff");
            else setUserRole("customer");
            setAuthLoading(false);
          })
          .catch(() => {
            setIsLoggedIn(false);
            setUserRole(null);
            setRoles([]);
            setAuthLoading(false);
          });
      } else {
        setIsLoggedIn(false);
        setUserRole(null);
        setActiveAccount(null);
        setRoles([]);
        setAuthLoading(false);
      }
    });

    return () => {
      isMounted = false;
    };
  }, []);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider theme={theme}>
          <MsalProvider instance={msalInstance}>
            <AuthContext.Provider
              value={{
                activeAccount,
                userRole,
                roles,
                isLoggedIn,
                authLoading,
                setActiveAccount,
                setUserRole,
                setRoles,
                setIsLoggedIn,
              }}
            >
              <CssBaseline />
              <NotificationProvider>
                <MenuProvider>
                  <OrderProvider>
                  <Layout>
                    {children}
                  </Layout>
                  </OrderProvider>
                </MenuProvider>
                <NotificationSystem />
              </NotificationProvider>
            </AuthContext.Provider>
          </MsalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
