name: Build Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-frontend:
    name: Build Next.js Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/front-end

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: "./src/front-end/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  build-backend:
    name: Build .NET Core API
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/back-end

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release
